# Generated by Django 5.0.1 on 2025-08-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CochraneReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_id",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., CD000979",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("authors", models.CharField(blank=True, max_length=500, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-publication_date", "title"],
                "indexes": [
                    models.Index(
                        fields=["review_id"], name="cochrane_co_review__575ac2_idx"
                    ),
                    models.Index(
                        fields=["-publication_date"],
                        name="cochrane_co_publica_92d26a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CochraneSoFEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("population", models.TextField(blank=True, null=True)),
                ("intervention", models.TextField(blank=True, null=True)),
                ("comparison", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("measure", models.CharField(blank=True, max_length=255, null=True)),
                ("effect", models.CharField(blank=True, max_length=255, null=True)),
                ("ci_lower", models.CharField(blank=True, max_length=255, null=True)),
                ("ci_upper", models.CharField(blank=True, max_length=255, null=True)),
                ("significant", models.BooleanField(blank=True, null=True)),
                (
                    "num_participants",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "num_studies",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certainty_of_evidence",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reasons_for_grade", models.TextField(blank=True, null=True)),
                ("risk_of_bias", models.BooleanField(blank=True, null=True)),
                ("imprecision", models.BooleanField(blank=True, null=True)),
                ("inconsistency", models.BooleanField(blank=True, null=True)),
                ("indirectness", models.BooleanField(blank=True, null=True)),
                ("publication_bias", models.BooleanField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sof_entries",
                        to="cochrane.cochranereview",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cochrane SoF Entries",
                "ordering": ["review", "id"],
                "indexes": [
                    models.Index(
                        fields=["review"], name="cochrane_co_review__b08581_idx"
                    ),
                    models.Index(
                        fields=["certainty_of_evidence"],
                        name="cochrane_co_certain_688c70_idx",
                    ),
                ],
            },
        ),
    ]
